/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectooficial;
import java.awt.BorderLayout;
import java.io.File;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.JScrollPane;
/**
 *
 * @author Jonathan
 */
public class Video extends javax.swing.JPanel {

    /**
     * Creates new form Videos
     */
    public  JFXPanel jfxPanel = new JFXPanel(); 
    private File file;
    private MediaPlayer oracleVid;
    private String video;
    public Video(String video)
    {
        this.video = video;
        initComponents();
        createScene();      
        setLayout(new BorderLayout());
        add(jfxPanel,BorderLayout.CENTER);
        
    }
        private void createScene(){
        Platform.runLater(new Runnable() {
             @Override
             public void run() {                 
                file = new File(video);                                  
                    oracleVid = new MediaPlayer(                                       
                        new Media(file.toURI().toString())
                    );
                    //se añade video al jfxPanel
                    jfxPanel.setScene(new Scene(new Group(new MediaView(oracleVid))));                    
                    oracleVid.setCycleCount(MediaPlayer.INDEFINITE);//repite video
                    
             }
        });
    }
    
    public void play(){
        oracleVid.play();
    }
    public void pausa(){
        oracleVid.pause();
    }
    public void silencio(){
        oracleVid.setMute(true);
    }
    public void sonido (){
        oracleVid.setMute(false);
    }
    public void volumen(int volumen){
        
        oracleVid.setVolume(volumen);
    }

    public void setVideo(String video) {
        this.video = video;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(165, 158));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
